import os
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("DISCORD_TOKEN")

CHAT_XP = 15
SPAWN_MESSAGE_COUNT = 30
SPAWN_CHANCE = 0.34
DESPAWN_TIME = 300
ARISE_SUCCESS_RATE = 0.55
MAX_TOTAL_SHADOWS = 16
MAX_DUPLICATE_SHADOW = 3
